# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-20 04:47
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_available', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Monto disponible')),
                ('amount_locked', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name=b'Monto bloqueado')),
                ('amount_invested', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name=b'Monto invertido')),
                ('customer_dwolla', models.TextField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'ID de Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveIntegerField(choices=[(1, b'Amigos'), (2, b'Cancelada'), (3, b'En proceso')], default=3, validators=[django.core.validators.MaxValueValidator(3)], verbose_name=b'Estado')),
                ('friend1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend1', to=settings.AUTH_USER_MODEL, verbose_name=b'ID de Usuario 1')),
                ('friend2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend2', to=settings.AUTH_USER_MODEL, verbose_name=b'ID de Usuario 2')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False, verbose_name=b'Estado')),
                ('amount_loan', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name=b'Monto del prestamos')),
                ('amount_interest', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name=b'Monto del interes')),
                ('friendship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Friendship', verbose_name=b'ID de Amistad')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False, verbose_name=b'Estado')),
                ('amount_available', models.DecimalField(decimal_places=2, max_digits=12, verbose_name=b'Monto disponible')),
                ('amount_request', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name=b'Monto sugerido')),
                ('interest', models.DecimalField(decimal_places=2, max_digits=12, verbose_name=b'Interes')),
                ('commentary', models.CharField(max_length=150, verbose_name=b'Comentario')),
                ('date_return', models.PositiveIntegerField(verbose_name=b'D\xc3\xadas de devoluci\xc3\xb3n')),
                ('date_expiration', models.DateField(verbose_name=b'Fecha de Expiraci\xc3\xb3n')),
                ('deadline', models.DateField(verbose_name=b'Fecha l\xc3\xadmite')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name=b'Fecha de creaci\xc3\xb3n')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'ID de Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=150, verbose_name=b'Mensaje')),
                ('date', models.DateField(auto_now_add=True, verbose_name=b'Fecha')),
                ('read', models.BooleanField(default=False, verbose_name=b'Le\xc3\xaddo')),
                ('request_id', models.PositiveIntegerField(verbose_name=b'ID del Tipo')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name=b'Tipo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'ID de Usuario')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_visit', models.PositiveIntegerField(default=0, verbose_name=b'N\xc3\xbamero de visita')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'C\xc3\xb3digo')),
                ('pin', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Descripci\xc3\xb3n')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name=b'Fecha de nacimiento')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name=b'Tel\xc3\xa9fono')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'profile/', verbose_name=b'Imagen de perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'ID de Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.LoanRequest', verbose_name=b'ID de Solicitud'),
        ),
    ]
